# This file was generated by @liquid-labs/catalyst-builder-workflow-local-make-
# node. Refer to https://npmjs.com/package/@liquid-labs/catalyst-builder-workflow-
# local-make-node for further details

SRC:=src
DIST:=dist
TEST_STAGING:=test-staging
QA:=qa
