# This file was generated by @liquid-labs/catalyst-builder-workflow-local-make-
# node. Refer to https://npmjs.com/package/@liquid-labs/catalyst-builder-workflow-
# local-make-node for further details

#####
# build dist/resource-model.js
#####

CATALYST_RESOURCE_MODEL_JS:=$(DIST)/resource-model.js
CATALYST_RESOURCE_MODEL_JS_ENTRY=$(SRC)/index.js
BUILD_TARGETS+=$(CATALYST_RESOURCE_MODEL_JS)

$(CATALYST_RESOURCE_MODEL_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_RESOURCE_MODEL_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/resource-model.js
#####
